name: Lint

on:
  push:
    branches-ignore: [main, master]
  pull_request:
    branches: [main, master]

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin master:master

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_YAML_PRETTIER: false